name: DeployS3
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ himanshugarg/cicd/ghactions ]


  workflow_dispatch:

jobs:
  s3_push:
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3

      - name: Configure AWS Creds
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-service-role

      - name: Upload file to S3
        run: aws s3 sync catalog s3://${{ secrets.BUCKET_NAME }}/catalog/ --exclude "*" --include "*.yml" --include "*.yaml"
