name: DeployS3
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


  workflow_dispatch:

jobs:
  s3_push:
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3

      - name: Configure AWS Creds
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::$AWS_ACCOUNT_ID:role/github-actions-service-role

      - name: Upload file to S3
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: aws s3 sync catalog s3://$BUCKET_NAME/catalog/ --exclude "*" --include "*.yml" --include "*.yaml"
